### ISSUE TITLE
Not working with latest Paper builds

### ISSUE THREAD

**Issue by Geitenijs** [bergerhealer/Light-Cleaner#13]
Getting the following error when trying to use /cleanlight on the most recent version of Paper:
https://pastebin.com/A8rHHPXy

**Comment by FrozenBeard** [comment]
I also dont have it working in Paper

**Comment by Combustible** [comment]
Works fine for me with a more recent paper build. This should probably be closed?

**Comment by bergerkiller** [comment]
This issue was indeed fixed in BKCommonLib (added support), so if it isnt working for you, use a development build
