### ISSUE TITLE
Feature request: Config option to tune the number of chunks processed per tick

### ISSUE THREAD

**Issue by Combustible** [bergerhealer/Light-Cleaner#16]
I'm using the LightCleaner API alongside Fast Async World Edit. Basically spawning in a big area (100k - 10M blocks) and then adding the chunks to LightCleaner's queue to fix. It works great! 

I'm working on a bit of server optimization, and on my configuration lightcleaner normally runs in around 35ms per tick, which is low/excellent but still a majority of the 50ms/tick target. I'd love to be able to configure light cleaner to process a smaller number of chunks per tick so as to push this down even futher. 

Thanks for a great plugin!

**Comment by bergerkiller** [comment]
This feature was added, in addition chunks are now loaded asynchronously, which means only the reading/applying of chunk data incurs a tps overhead currently.

**Comment by Combustible** [comment]
A bit late - but thank you!
