### ISSUE TITLE
Lightcleaner console error

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/Light-Cleaner#19]
Using the latest BKCommonLib and Lightcleaner build from https://ci.mg-dev.eu
Server version 1.14.4

Error: https://pastebin.com/AaDcnLE0

**Comment by bergerkiller** [comment]
> no such class: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap

This was caused by paperspigot moving the path of the class, it was fixed in BKCommonLib since then
