### ISSUE TITLE
Light-cleaner is not working with latest BKCommonLib-1.14.4-v2-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Tsoccerguy3** [bergerhealer/Light-Cleaner#20]
After running /cleanlight , light is no longer fixed using latest BKCommonLib-1.14.4-v2-SNAPSHOT

![2019-10-21_21 49 17](https://user-images.githubusercontent.com/22108822/67254903-80ad2200-f44d-11e9-9312-a025698157c3.png)

**Comment by bergerkiller** [comment]
I assume this issue is fixed with the latest dev builds of BKCommonLib, as I've used cleanlight on 1.14.4 before when checking version compatibilities a couple days ago. If the issue isn't fixed, you can re-open.
