### ISSUE TITLE
Flag to remove lighting first, then re-light chunks.

### ISSUE THREAD

**Issue by mibby** [bergerhealer/Light-Cleaner#22]
Would it be possible to add a flag to the /cleanlight command to remove chunk lighting, then relight the chunks? As it doesn't seem to fix lighting in some worldedit paste operation lighting bugs.

**Comment by bergerkiller** [comment]
It already does that right now. The only lighting kept is a 1-block edge around the chunk area being cleaned.

**Comment by mibby** [comment]
Ah, never noticed it. It must only send the finished update packet after it has relit everything. Thanks, will close this request then. :)

**Comment by bergerkiller** [comment]
Yeah, the newer dev builds of BKCommonLib + Light Cleaner should fix that not resending issue, it had to do with some asynchronous access bug
