### ISSUE TITLE
Cleanlight doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [bergerhealer/Light-Cleaner#24]
If you type _/cleanlight_ with or without radius, you will get a positive feedback ingame, but nothing happens. The following error appears in the log: https://pastebin.com/ufKkURdP
The error happens world independent.

BKCommonLib version 1.15.2-v4-SNAPSHOT
LightCleaner version 1.15.2-v1
Paper 1.15.2 - 240
FAWE: 1.15.2 - 197

**Comment by weeryan17** [comment]
`Server not supported, initialization failed`
Are you actually using paper, or a weird fork of paper?

**Comment by brandinio** [comment]
I am also getting the same issue with Paper - 245, same version of LightCleaner (1.15.2-v1). So glad I saw this comment because I genuinely thought maybe the server host banned the plugin or something

**Comment by TheoRetisch1** [comment]
I'm using paper, but I activated _no-tick-view-distance 10_ which was implemented yesterday. Could this be releated?

**Comment by weeryan17** [comment]
Is it still an issue on newer versions of paper (so `260`)?

**Comment by TheoRetisch1** [comment]
Yes it does, tested it a minute ago

**Comment by bergerkiller** [comment]
Alright, I'll have to go and fix support with the newest paper then. Something they changed must've bricked it

**Comment by brandinio** [comment]
So checking back on the logs, it doesn't seen to be showing anything like an error or a warning on loading up the two plugins, but I did notice this warning straight after executing /cleanlight world... https://pastebin.com/HwBuwTJn

**Comment by bergerkiller** [comment]
In the most likely case, paper devs de-obfuscated that field. Should be an easy fix

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/BKCommonLib/commit/855f06a704f7bca8993b1d5899f27b5d6c622e0f

https://ci.mg-dev.eu/job/BKCommonLib/766/

**Comment by TheoRetisch1** [comment]
Thanks it works :)
