### ISSUE TITLE
Server Crash on a voidmap

### ISSUE THREAD

**Issue by TheoRetisch1** [bergerhealer/Light-Cleaner#32]
The server crashes after some spots have been processed with cleanlight. The error occurs only on a voidmap.
Crash: https://pastebin.com/qsjvWH9g

Paper-138 (MC: 1.16.1)
LightCleaner version 1.16.2-v1
BKCommonLib version 1.16.2-v1

**Comment by bergerkiller** [comment]
I tried it on a the_end world but no such crash occurs, what kind of void map do I need to reproduce this problem?

**Comment by TheoRetisch1** [comment]
In the end I have no problems either. The crashes happen irregularly and relatively rarely with a real voidmap. In singleplayer you can simply select the option in multiplayer you can generate one with a plugin like this (https://www.spigotmc.org/resources/voidgenerator.25391/). 
Do you think it might have something to do with the following older Paper Patch (https://github.com/PaperMC/Paper/pull/3506) and not with LightCleaner?

**Comment by bergerkiller** [comment]
Yeah it can definitely have to do with that. Or with BKCommonLib doing something outdated that causes trouble in the new paperspigot. It's worth checking if the same problems also occur on normal spigot.

For sure, I never write null nibble data to chunks from light cleaner, so the issue isn't as simple as that unfortunately.

**Comment by bergerkiller** [comment]
I installed voidgenerator and did a clean but no crash for me. Im on paperspigot 1.16.2-168 tho. Maybe they patched it. I'll check 1.16.1

**Comment by TheoRetisch1** [comment]
Ok, we will update to 1.16.2 the coming week and check out the newest paper builds. If required we will report the problem to Paper. Thanks for your help and all the effort. Have a great day!
