### ISSUE TITLE
ThreadedAnvilChunkStorage (world): All chunks are saved

### ISSUE THREAD

**Issue by x1p** [bergerhealer/Light-Cleaner#34]
Today I saw this spam on the server. CPU much too high for the amount of players, which was zero.
```
[09:01:13] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:19] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:01:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
```

I did a timings report and BKCommonLib and LightCleaner stuck out.
I unloaded LightCleaner with plugman and the spam stopped.
(The pending file was about 155 kb in size. I deleted it, loaded the plugin again)

I'm not sure which plugin is the cause of this. I guess LightCleaner because this performs stuff and BKCommonLib probably not.

BKCommonLib-1.16.3-v1
LightCleaner-1.16.3-v1
Paper (fork) 1.16.3

**Comment by bergerkiller** [comment]
It performs saving of worlds to free memory, while processing. Are you low on memory by chance? And is there a worldwide cleaning operation scheduled? (/cleanlight status). Mind that it saves scheduled operations and continues on restart.

**Comment by x1p** [comment]
I'm not at all low on mem. Mostly 3gig of RAM free
I didn't know that command existed, so I didn't do that. Now it's not busy anymore but that is obvious.
Maybe the pending file was poluted

**Comment by bergerkiller** [comment]
Do you use a form of automatic cleaning? Triggered by (async) worldedit, or chunkgen? Something may have happened that triggered loads of operations

**Comment by x1p** [comment]
> Triggered by (async) worldedit, or chunkgen?
Pregen world, currently no async worldedit.
It started about 5 minutes after some players teleported to a dormant world (not used very often)

**Comment by bergerkiller** [comment]
`autoCleanEnabled` will cause it to clean up newly generated areas of the world. Perhaps a lot of chunks were generated and it was falling behind processing them all?

**Comment by x1p** [comment]
Generating chunks, when it's a pre-regenerated map. I find that rather peculiar. xD

Anyway, it's resolved for now. I hope this doesn't happen again.

**Comment by bergerkiller** [comment]
well, technically its when a chunk is populated, not generated. Maybe something really strange happened that it started populating chunks (adding stuff like villages) when it was pre-generated. Or a player started flying to the generated border.

if it happens again, theres /cleanlight abort to make a quick end to it.

**Comment by x1p** [comment]
Nice to know that there is a command for that 👍
