### ISSUE TITLE
Cleanlight doesn't work with Tuinity-Starlight

### ISSUE THREAD

**Issue by TheoRetisch1** [bergerhealer/Light-Cleaner#37]
Cleanlight doesn't work reliably under Tuinity-Starlight. Often the light is only partially or not completely repaired. There are no errors in the log.
Tuinity-Starlight (https://github.com/Spottedleaf/Starlight) offers a completely renewed light calculation that is far superior to vanilla or paper calculations. Therefore it would be fantastic if you could support this light engine.

Tuinity-Starlight 1.16.4 build 7 (https://ci.tivy.ca/job/Tuinity-Starlight/)
BKCommonLib 1.16.4-v3-SNAPSHOT build 966
LightCleaner-1.16.4-v2 build 99

**Comment by bergerkiller** [comment]
Do note that I don't use the light engine of the server whatsoever, but them using a custom engine would explain why setting light values for a 16x16x16 section of blocks doesn't work.

**Comment by bergerkiller** [comment]
Working on some stuff, no guarantees

**Comment by TheoRetisch1** [comment]
Awesome, I'm excited 👍

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/BKCommonLib/commit/794d0e4d5aa69e848688703cfbae94abedfe05c0

No guarantees of stability, but at least on my end, it works to read & apply the lighting data. I don't really touch the engine itself as that appears to be more geared towards caching small changes / spreading of light.

https://ci.mg-dev.eu/job/BKCommonLib/970/

**Comment by TheoRetisch1** [comment]
It works like a charm! Thank you 💯 🥇
