### ISSUE TITLE
cleanlight world not working

### ISSUE THREAD

**Issue by sigmaroot** [bergerhealer/Light-Cleaner#4]
Hey, first of all: great plugin!

/cleanlight <radius> works fine, but the /cleanlight world does not at all.

I've got a pre-generated world (filled with WorldBorder) and tried to fix all light bugs. But there are still bugs:

https://imgur.com/a/ul3xy

**Comment by sigmaroot** [comment]
FYI: When I use /cleanlight with a radius that is great enogh for the whole world, it is working, I just have to trim the new generated chunks beyond the world border

**Comment by bergerkiller** [comment]
oh, I didn't know this was broken since it worked when I used it. You can check if it shows cleaning status correctly with /cleanlight status. Strange...what server is this on? Maybe I need a particular server software to reproduce it.

**Comment by sigmaroot** [comment]
That was on paper spigot runnig version git-Paper-1201 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by GeekzGamingz** [comment]
Same problem.

**Comment by bergerkiller** [comment]
I suppose it is worth looking into again, I will put it back on the list of priority issues

**Comment by bergerkiller** [comment]
For now this issue continues under https://github.com/bergerhealer/Light-Cleaner/issues/3
