### ISSUE TITLE
Eating a lot of server resource on 1.16.4

### ISSUE THREAD

**Issue by Tsoccerguy3** [bergerhealer/Light-Cleaner#40]
Causing a lot of lag even when not in use . 30 sec to fix light in 10 chunks

The timing report may help
https://timings.aikar.co/?id=6b66fb006266466481c13eb7de9fd074#plugins

**Comment by bergerkiller** [comment]
It's definitely in use, maybe the automatic cleaning is enabled? Worldedit and chunk gen? Check config.yml

**Comment by Tsoccerguy3** [comment]
config yml

#> This is the configuration of Light Cleaner, in here you can enable or disable features as you please

# The minimum amount of memory (in MB) allowed while processing chunk lighting
# If the remaining free memory drops below this value, measures are taken to reduce it
# Memory will be Garbage Collected and all worlds will be saved to free memory
# The process will be stalled for so long free memory is below this value
minFreeMemory: 400

# Whether to skip processing chunks at the edge of the world
# Setting this to true prevents additional chunks being generated there
# This does mean the border chunks do not get cleaned
skipWorldEdge: true

# Sets whether lighting is cleaned up for newly generated chunks
# This will eliminate dark shadows during world generation
autoCleanEnabled: false

# Sets whether lighting is cleaned up when players perform WorldEdit operations
# This is primarily useful for FastAsyncWorldEdit
autoCleanWorldEditEnabled: false

# How many chunks are asynchronously loaded at the same time
# Setting this value too high may overflow the internal queues. Too low and it will idle too much.
asyncLoadConcurrency: 50

# A list of world names that have saving disabled
# Light Cleaner will not save these worlds to free up memory,
# and will not write persistent PendingLight.dat entries for these worlds
unsavedWorldNames: []

**Comment by bergerkiller** [comment]
That does look all disabled, what does /cleanlight status say? A /cleanlight abort should stop whatever is scheduled.

Might be someone initiated a worldwide clean

**Comment by Tsoccerguy3** [comment]
I checked for a instance running , none are . It could be a lot of things . I will check some more things 
https://timings.aikar.co/?id=112c585a9f5f4621ba80c694ef6e2dad#plugins

**Comment by bergerkiller** [comment]
The time spent is in the fill() method, where it reads the current chunk data into memory. It is possible that this gets called much later, as there was no check whether the task was aborted. Ive added an aborted check so that it will not spend time here when /cleanlight abort is done. https://github.com/bergerhealer/Light-Cleaner/commit/42ed426f9b2464c7ed5b8774474f6462a9fb152f

**Comment by bergerkiller** [comment]
To further diagnose it, Ive added extra timings to some parts of the fill() method. Can you run another timings with this version to retrieve this information? It should further narrow down what process takes so very long in your situation. https://ci.mg-dev.eu/job/Light-Cleaner/107/

**Comment by Tsoccerguy3** [comment]
looks good 

https://timings.aikar.co/?id=b02a5562882c4f0ca8bada0f7ff6a68f#plugins

**Comment by Tsoccerguy3** [comment]
FAWE is playing around with adding code to fix lighting automatically . They just removed or disabled the code today . something was broken

**Comment by Tsoccerguy3** [comment]
resolved
