### ISSUE TITLE
Cleanlight doesn't handle worlds unloading gracefully

### ISSUE THREAD

**Issue by libraryaddict** [bergerhealer/Light-Cleaner#50]
When a server loads and unloads worlds, cleanlight doesn't seem to handle it gracefully. 

Not recognizing when a world is no longer in use, and trying to continue to clean light on a world that hasn't been loaded since startup.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/Light-Cleaner/131/ Don't think much more is needed.

**Comment by libraryaddict** [comment]
What about when the server starts up?

Not sure if that change would catch every scenario the world isn't loaded.

Mostly thinking of the error spam I get when the server starts up with world not found.

Not sure when it saves pending cleans, but a normal server shutdown may not call unload. Pending verification. A server crash definitely wouldn't call unload.

Basically just worth checking to make sure the world exists for saved clean tasks before trying to resume them.

**Comment by bergerkiller** [comment]
Oh lord I just realized what its doing haha. Let me fix that.

```
                    World world = Bukkit.getWorld(worldName);
                    if (world == null) {
                        // Load it?
                        if (new File(Bukkit.getWorldContainer(), worldName).exists()) {
                            world = Bukkit.createWorld(new WorldCreator(worldName));
                        } else {
                            missingWorlds.add(worldName);
                        }
                    }
```

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/Light-Cleaner/132/ Throws out operations on load for worlds that arent loaded and dont get loaded within 2 server ticks.

**Comment by libraryaddict** [comment]
Thanks!

Got worried when I saw that code snippet, thought that was your new code 😜

Unfortunately won't be able to make use of this build for a few days as I'm unavailable, but I don't think there should be any problems.

Thanks again!
