### ISSUE TITLE
Please Update to 1.20!

### ISSUE THREAD

**Issue by SkyKingPX** [bergerhealer/Light-Cleaner#58]
please

**Comment by bbayu123** [comment]
Be patient. We are all human, we have lives, we take time to actually do stuff.
Give us some time, monitor our discord.

**Comment by SkyKingPX** [comment]
I know. I just wanted to know how you were going.

**Comment by bbayu123** [comment]
All our progress and updates are in our Discord server.

**Comment by SkyKingPX** [comment]
Thanks. Can you send the Link to the Discord?

**Comment by bergerkiller** [comment]
https://discord.gg/wvU2rFgSnw

**Comment by SkyKingPX** [comment]
Thanks
