### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by BloodEko** [bergerhealer/Light-Cleaner#6]
The plugin isn't starting in spigot 1.12.2 , any ideas ?

**Comment by bergerkiller** [comment]
I'd need more information. Is the latest version of BKCommonLib installed? Anything in the logs?

**Comment by BloodEko** [comment]
I tried to use the latest version of LiteCleaner with the latest version of BKCommonLib.
My Spigot is about 70 builds behind (1.12.2) , no luck with this setup.

But then, I tried LightCleaner 1.12-v4  it actually loaded and worked without problems! Maybe you added something depending on a newer spigot version recently ?

**Comment by bergerkiller** [comment]
Perhaps a field change between the builds that went unnoticed? Does it not work without any errors, or is anything showing up in the logs? I'll do a version diff between the versions of spigot.

It would help if you could post the exact version string of the spigot version that doesnt work

**Comment by BloodEko** [comment]
Actually it seems like the latest version is loading now on my server and I haven't updated Spigot.
Sorry, that i can't provide an error case anymore.
Great plugin, keep going!
