### ISSUE TITLE
minFreeMemory Not Functioning

### ISSUE THREAD

**Issue by GeekzGamingz** [bergerhealer/Light-Cleaner#8]
The minFreeMemory config is not working properly. If my memory is over 400 in use (which is usually the case), CleanLight no longer functions even when I set this up to as high as 5000.

**Comment by bergerkiller** [comment]
min free memory makes the plugin disable when the amount of free memory LEFT is below that threshold. This is meant to prevent an out of memory situation. Setting it to a very high value will obviously disable the plugin permanently while it waits for free memory that will never exist.

Unless you meant it in a different way, if you want to push your luck with low memory situations, set the number to a very low value instead. 0 will disable checking memory entirely. I strongly discourage doing any world-wide cleaning in this situation.

**Comment by GeekzGamingz** [comment]
Thank you for that clarification!
